homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 104
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages


# Enables the frontend
frontend:

# Enables configuration UI
config:

mycroft:
  host: 10.0.0.176

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret base_url

device_tracker:
  - platform: gpslogger
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_user
    password: !secret unifi_pw
    verify_ssl: False
  - platform: bluetooth_tracker
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

ios:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

light:
  - platform: hue
    allow_unreachable: true
    allow_hue_groups: false

alarm_control_panel:
  platform: alarmdotcom
  username: !secret alarm_username
  password: !secret alarm_password

################################################
## Component Includes (Merge List)
################################################
automation: !include_dir_merge_list automation
group: !include_dir_merge_named group
zone: !include_dir_merge_list zone

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
