##############################################################
## Packages / Wife Alarms
##############################################################

automation:
  - alias: 'Medicine Reminder'
    condition:
    - condition: state
      entity_id: device_tracker.sheenas_iphone
      state: 'home'
    trigger:
      - platform: time
        at: '6:30:00'
    action:
      - service: script.voice_notify_all
        data_template:
          value1: Don't forget Sheena to take your pill, no babies please.
          value2: ""
