##############################################################
## Packages / Wife Alarms
##############################################################

automation:
  - alias: 'Medicine Reminder'
    condition:
      - condition: state
        entity_id: device_tracker.sheenasiphone
        state: 'home'
    trigger:
      - platform: time
        at: '6:30:00'
    action:
      - service: notify.notify
        data:
          message: "Don't forget Sheena to take your pill, no babies please."
          title: "Medicine Reminder"
